SkillWise/Models/Skill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SkillWise.Models
{
    public class Skill
    {
        public int SkillId { get; set; }

        
        [StringLength(50, MinimumLength = 3)]
        [Required(ErrorMessage = "Please enter the name of the skill.")]
        [DataType(DataType.Text)]
        public string Title { get; set; }

        
        [StringLength(100, MinimumLength = 3)]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [Display(Name = "Public")]
        public bool IsPublic { get; set; }

        [Display(Name = "Experience")]
        public Experience Experience { get; set; }

        public DateTime _timestamp { get; set; } = DateTime.Now;

        // Relationships

        // User
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        // Assignments / Tasks
        public virtual List<SkillTask> SkillTasks { get; set; }
        public virtual List<SkillHour> SkillHours { get; set; }
    }

    public enum Experience
    {
        Student, Moderate, Expert
    }
}

SkillWise/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SkillWise.Models;
using SkillWise.Models.Services;

namespace SkillWise.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private ISkillService _skillService;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public DashboardController(ISkillService skillService, SignInManager<ApplicationUser> signInManager)
        {
            _skillService = skillService;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            var userId = _signInManager.UserManager.GetUserId(User);
            var model = _skillService.GetAll(userId);
            
            return View(model);
        }

        
    }
}

SkillWise/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SkillWise.Models;
using SkillWise.Models.Services;
using SkillWise.Models.ViewModels;

namespace SkillWise.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillService _skillService;
        private readonly UserManager<ApplicationUser> _userManager;
        
        public SkillController(ISkillService skillService, UserManager<ApplicationUser> userManager)
        {
            _skillService = skillService;
            _userManager = userManager;
            
        }
        

        // Get: Details view
        public IActionResult View(int id)
        {
            
            var model = _skillService.GetById(id);
            var userId = _userManager.GetUserId(User);

            if( model == null || model.UserId != userId)
            {
                return NotFound();
            }

            ViewData["SumOfHours"] = _skillService.GetSumOfHours(id).ToString();
            return View(model);
        }

        // Get: Create
        public IActionResult Create()
        {
            return View();
        }

        // Post: create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Skill skill)
        {
            if (ModelState.IsValid)
            {

                var userId = _userManager.GetUserId(User);
                skill.UserId = userId;
                _skillService.Save(skill);

                return RedirectToAction("Index", "Dashboard");

            }

            return View();
        }

        // Get: Details
        public IActionResult Details(int id)
        {
            var model = _skillService.GetById(id);
            var userId = _userManager.GetUserId(User);

            if(model == null || userId != model.UserId)
            {
                return NotFound();
            }


            return View(model);
        }

        // Post: update details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateDetails(Skill skill)
        {
            if (ModelState.IsValid)
            {
                skill.UserId = _userManager.GetUserId(User);
                _skillService.Update(skill);
                return RedirectToAction("View", "Skill", new { id = skill.SkillId });

            }

            return View();
        }

        // Get: Confirm delete page {skillid}
        public IActionResult ConfirmDelete(int id)
        {
            var model = _skillService.GetById(id);
            var userId = _userManager.GetUserId(User);

            if( model == null || model.UserId != userId )
            {
                return NotFound();
            }

            return View(model);
        }

        // Post: confirm delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Skill model)
        {
            var userId = _userManager.GetUserId(User);

            _skillService.Delete(model);
            return RedirectToAction("Index", "Dashboard");
        }
    }
}

SkillWise/Controllers/SkillHourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SkillWise.Models;

namespace SkillWise.Controllers
{
    public class SkillHourController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public SkillHourController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public string Index()
        {
            return "The index page has not been implemented yet.";
        }

        // Get: /skillhour/create/:skillid
        public IActionResult LogHours(int? id)
        {
            if( id == null)
            {
                return NotFound();
            }

            ViewData["SkillId"] = id;

            return View();
        }
        
        // Post LogHours
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LogHours(SkillHour skillHour)
        {

            if (ModelState.IsValid)
            {
                _dbContext.SkillHours.Add(skillHour);
                _dbContext.SaveChanges();

                return RedirectToAction("View", "Skill", new { id = skillHour.SkillId });
            }

            ViewData["SkillId"] = skillHour.SkillId;
            return View(skillHour);
        }

    }
}

SkillWise/Controllers/SkillTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SkillWise.Models;
using SkillWise.Models.Services;

namespace SkillWise.Controllers
{
    public class SkillTaskController : Controller
    {
        private readonly ISkillService _skillService;
        private readonly UserManager<ApplicationUser> _userManager;

        public SkillTaskController(ISkillService skillService, UserManager<ApplicationUser> userManager)
        {
            _skillService = skillService;
            _userManager = userManager;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create(int id)
        {
            ViewData["SkillId"] = id;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SkillTask skillTask)
        {
            if (ModelState.IsValid)
            {
                _skillService.AddTask(skillTask);
                return RedirectToAction("View", "Skill", new { id = skillTask.SkillId });
            }

            ViewData["SkillId"] = skillTask.SkillId;
            return View(skillTask);
            
        }


        public IActionResult Details(int id)
        {
            var model = _skillService.GetTaskById(id);

            if( model == null)
            {
                return NotFound();
            }

            if(model.Skill.UserId != _userManager.GetUserId(User))
            {
                return NotFound();
            }


            return View(model);
        }

        public IActionResult SetComplete(int id)
        {
            var userId = _userManager.GetUserId(User);
            var task = _skillService.SetTaskToComplete(id, userId);
            
            if(task == null)
            {
                return NotFound();
            }

            return RedirectToAction("View", "Skill", new { id = task.SkillId });
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateTask(SkillTask skillTask)
        {
            if (ModelState.IsValid)
            {
                var result = _skillService.UpdateTask(skillTask);

                if(result == null)
                {
                    return NotFound();
                }

                return RedirectToAction("View", "Skill", new { id = skillTask.SkillId });
            }

            return View(skillTask);
        }

        public IActionResult DeleteTask(int id)
        {
            var userId = _userManager.GetUserId(User);
            var skillId = _skillService.DeleteTask(id, userId);

            if(skillId == null)
            {
                return NotFound();
            }

            return RedirectToAction("View", "Skill", new { id = skillId });
        }

    }
}

SkillWise/Views/Skill/ConfirmDelete.cshtml
@model Skill
@{
    ViewData["Title"] = "Confirm Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@section NavOptions {
    <a asp-controller="Skill" asp-action="View" asp-route-id="@Model.SkillId">&larr;</a>
}

<h1 class="text-center pt-5 pb-3">Do you really want to delete?</h1>

<form asp-controller="Skill" asp-action="Delete" method="post">
    <input type="hidden" name="SkillId" value="@Model.SkillId" />
    <div class="row col-6 block m-auto">
        <div class="form-group row col-lg-12">
            <div class="col-lg-12">
                <h4 class="text-center">@Model.Title</h4>
            </div>
            <div class="col-lg-12">
                <p class="text-danger text-center">You cannot reverse after deleting!</p>
            </div>
        </div>
        <hr/>
        <div class="form-group row col-lg-12">
            <div class="col-sm-4">
                <button type="submit" class="btn btn-danger">Confirm delete</button>
            </div>
            <div class="col-sm-4">
                <a asp-controller="Skill" asp-action="View" asp-route-id="@Model.SkillId" class="btn">Cancel</a>
            </div>

        </div>
    </div>
</form>

SkillWise/Views/Skill/Create.cshtml
@model Skill
@{
    ViewData["Title"] = "Start a new skill";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@section NavOptions {
    <a asp-controller="Dashboard" asp-action="Index">&larr;</a>
}

<h1 class="text-center">Start a new skill</h1>
<br />
<form asp-controller="Skill" asp-action="Create" method="post">
    <div class="block row col-lg-6 m-auto">

        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="Title"></label>
            </div>
            <div class="col-sm-12">
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="col-sm-12">
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="Description"></label>
            </div>
            <div class="col-sm-12">
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="col-sm-12">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="IsPublic"></label>
            </div>
            <div class="col-sm-12">
                <input asp-for="IsPublic" class="form-control" />
            </div>
        </div>
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="Experience"></label>
            </div>
            <div class="col-sm-12">
                <select asp-for="Experience" class="form-control">
                    <option value="Student">Student</option>
                    <option value="Moderate">Moderate</option>
                    <option value="Expert">Expert</option>
                </select>
            </div>
        </div>
        <div class="form-group row pt-2 col-12">

            <div class="col-lg-4 offset-lg-2">
                <button type="submit" class="btn btn-primary btn-block btn-lg">Start</button>
            </div>
            <div class="col-lg-4">
                <a href="/" class="btn btn-light btn-lg btn-block">Cancel</a>
            </div>
        </div>
    </div>
</form>

<partial name="_ValidationScriptsPartial" />

SkillWise/Views/Skill/Details.cshtml
@model Skill
@{
    ViewData["Title"] = @Model.Title;
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@section NavOptions {
    <a asp-controller="Skill" asp-action="View" asp-route-id="@Model.SkillId">&larr;</a>
}

<h1 class="text-center pt-3 pb-2">@Model.Title</h1>

<form asp-controller="Skill" asp-action="UpdateDetails" method="post">
    <div class="block row col-lg-6 m-auto">
        <input type="hidden" name="SkillId" value="@Model.SkillId" />
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="Title"></label>
            </div>
            <div class="col-sm-12">
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="col-sm-12">
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="Description"></label>
            </div>
            <div class="col-sm-12">
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="col-sm-12">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="IsPublic"></label>
            </div>
            <div class="col-sm-12">
                <input asp-for="IsPublic" class="form-control" />
            </div>
        </div>
        <div class="form-group row col-12">
            <div class="col-sm-12">
                <label asp-for="Experience"></label>
            </div>
            <div class="col-sm-12">
                <select asp-for="Experience" class="form-control">
                    <option value="Student">Student</option>
                    <option value="Moderate">Moderate</option>
                    <option value="Expert">Expert</option>
                </select>
            </div>
        </div>
        <div class="form-group row pt-2 col-12">

            <div class="col-lg-4 offset-lg-2">
                <button type="submit" class="btn btn-primary btn-block btn-lg">Update</button>
            </div>
            <div class="col-lg-4">
                <a asp-controller="Skill" asp-action="View" asp-route-id="@Model.SkillId" class="btn btn-light btn-lg btn-block">Cancel</a>
            </div>
        </div>

        <hr/>
        <div class="row form-group col-12">
            <a asp-controller="Skill" asp-action="ConfirmDelete" asp-route-id="@Model.SkillId" class="btn btn-outline-danger">Delete Skill</a>
        </div>
    </div>
</form>

<partial name="_ValidationScriptsPartial" />

SkillWise/Views/Skill/View.cshtml
@model Skill
@{
    ViewData["Title"] = Model.Title;
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@section NavOptions {
    <a asp-controller="Dashboard" asp-action="Index">&larr;</a>
}

    <div class="row col-md-8 block m-auto">
        <div class="col-12 p-5">
            <h1 class="text-center">
                <span style="display: block; font-size: 2.3em;">

                    <i class="fas fa-clock"></i><br/>@ViewData["SumOfHours"]
                </span> 
                <span class="text-muted">HOURS</span>
            </h1>
        </div>
       
        <div class="col-12">
            <hr/>
            <ul class="list-options">
                <li class="list-options-item float-right"><a asp-controller="SkillHour" asp-action="LogHours" asp-route-id="@Model.SkillId" class="btn btn-outline-primary">Log Hours</a></li>
                

                <li class="list-options-item float-right"><a asp-controller="Skill" asp-action="Details" asp-route-id="@Model.SkillId" class="btn btn-outline-info">Details</a></li>

            </ul>
        </div>  
    </div>
<br/><br/>
   
   <div class="row col-md-8 m-auto p-0 pb-5">
       @if (Model.SkillTasks.Any())
       {
           <div class="row col-md-12 mb-2">
               <div class="col-9">
                   <h4 class="text-muted">My Path</h4>
               </div>
               <div class="col-3 float-right">
                   <a asp-controller="SkillTask" asp-action="Create" asp-route-id="@Model.SkillId" class="btn btn-info">New Task</a>
               </div>
           </div>
           <div class="row col-12">
               <div class="list-group col-12">
                   @foreach (var task in Model.SkillTasks)
                   {

                   <a class="list-group-item list-group-item-action" asp-controller="SkillTask" asp-action="Details" asp-route-id="@task.SkillTaskId">
                       @if (task.IsComplete)
                       {
                           <i class="far fa-check-circle text-muted"></i>
                           <span style="text-decoration: line-through;">@task.Task</span>
                       }
                       else
                       {
                           if (task.IsPriority)
                           {
                               <i class="far fa-star text-muted"></i>
                           }
                           else
                           {
                               <span style="padding: 0 12px"></span> // Give a little spacing
                           }

                           // Add color if task is fundamental
                           if (task.IsFundamental)
                           {
                               <span class="text-primary">@task.Task</span>
                           }
                           else
                           {
                               <span>@task.Task</span>
                           }



                       }
                       <span class="float-right">&rarr;</span>
                       @if(task.RepeatOptions.ToString() != "None")
                       {
                       <br />
                       <span class="text-danger" style="font-size: .8em; padding-left: 22px;">
                           <i class="fas fa-redo-alt"></i>
                           @task.RepeatOptions
                       </span>
                       }
                   </a>
                   }
               </div>
           </div>
       }
   </div>